import fs from 'fs';
import path from 'path';
import { analyze } from './scan';
import { loadRateTableFromDistPath } from './rates-util';
import { runGuard } from './guard';

export function seedDemoUsage(outDir: string) {
  fs.mkdirSync(outDir, { recursive: true });
  const p = path.join(outDir, 'usage.jsonl');
  const now = Date.now();
  const lines: any[] = [];
  for (let i = 0; i < 60; i++) {
    lines.push({
      ts: new Date(now - i * 60_000).toISOString(),
      provider: 'openai',
      model: i % 4 === 0 ? 'gpt-5.2' : 'gpt-5-mini',
      endpoint: 'responses',
      attempt: 1,
      trace_id: 'demo-' + i,
      status: 'ok',
      prompt_tokens: 10_000 + (i % 10) * 1000,
      completion_tokens: 1200 + (i % 5) * 200,
      meta: { feature_tag: i % 2 ? 'summarize' : 'coding' }
    });
  }
  fs.writeFileSync(p, lines.map(x => JSON.stringify(x)).join('\n') + '\n');
  return p;
}

export function runQuickstart(cwd: string, opts: { port: number; budgetMonthlyUsd?: number }) {
  const outDir = path.join(cwd, 'aiopt-output');
  const usagePath = seedDemoUsage(outDir);

  const rt = loadRateTableFromDistPath();
  // Use the same normalizer as CLI scan/guard.
  const { readJsonl } = require('./io');
  const events = readJsonl(usagePath);
  const { analysis, savings, policy, meta } = analyze(rt, events);

  // write outputs (re-use scan writer by requiring dist is heavy; keep minimal here)
  fs.writeFileSync(path.join(outDir, 'analysis.json'), JSON.stringify(analysis, null, 2));
  fs.writeFileSync(path.join(outDir, 'report.json'), JSON.stringify({
    version: 3,
    generated_at: new Date().toISOString(),
    confidence: analysis.unknown_models?.length ? 'MEDIUM' : 'HIGH',
    warnings: [],
    assumptions: { quickstart: true },
    summary: {
      total_cost_usd: analysis.total_cost,
      estimated_savings_usd: savings.estimated_savings_total,
      routing_savings_usd: savings.estimated_savings_routing,
      context_savings_usd: savings.estimated_savings_context,
      retry_waste_usd: savings.retry_waste
    },
    top: {
      by_model: analysis.by_model_top,
      by_feature: analysis.by_feature_top
    },
    unknown_models: analysis.unknown_models || [],
    notes: []
  }, null, 2));
  fs.writeFileSync(path.join(outDir, 'cost-policy.json'), JSON.stringify(policy, null, 2));
  fs.writeFileSync(path.join(outDir, 'report.md'), '# AIOpt quickstart demo\n\nThis is a demo report generated by `aiopt quickstart --demo`.\n');

  // Run guard on the same log with traffic spike to show WARN
  const r = runGuard(rt, {
    baselineEvents: events,
    candidate: {
      contextMultiplier: 1.2,
      callMultiplier: 5,
      budgetMonthlyUsd: opts.budgetMonthlyUsd
    }
  });

  return { usagePath, outDir, guard: r, port: opts.port };
}
